### ISSUE TITLE
替换 urllib 为 request

### ISSUE THREAD

**Issue by isayme** [teambition/node-push#11]
soa 的经验, urllib 的可靠性没有 request 好

**Comment by orangemi** [comment]
可靠性是指什么？

**Comment by isayme** [comment]
@orangemi soa使用的时候, 同 request 前会偶尔出现 timeout 报错. 换了 request 之后少了很多.

**Comment by orangemi** [comment]
这是timeout默认值太低造成的，request没有默认的timeout吧

**Comment by orangemi** [comment]
request 默认使用Linux TCP connect timeout时间，20～120秒， urllib默认是5秒，timeout出现是显然的。

相关链接：
https://www.npmjs.com/package/request#requestoptions-callback
http://www.sekuda.com/overriding_the_default_linux_kernel_20_second_tcp_socket_connect_timeout

**Comment by isayme** [comment]
我们有设置timeout参数.
用urllib报的是`ResponseTimeoutError`错误, 不是connect timeout

**Comment by orangemi** [comment]
urllib config:
```
timeout Number | Array - Request timeout in milliseconds for connecting phase and response receiving phase. Defaults to exports.TIMEOUT, both are 5s. You can use timeout: 5000 to tell urllib use same timeout on two phase or set them seperately such as timeout: [3000, 5000], which will set connecting timeout to 3s and response 5s.
```

**Comment by isayme** [comment]
@leeqiang 测试跑了吗?
